server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-request: true
      force-response: true

spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true

  datasource:
    url: jdbc:h2:mem:store;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
