INSERT INTO SPREAD (SPREAD_ID, AMOUNT, PERSON, ROOM_ID, USER_ID, TOKEN, CREATE_AT) VALUES (1, 100, 4, 'dream0070', 22, 'gcM', now());
INSERT INTO SPREAD (SPREAD_ID, AMOUNT, PERSON, ROOM_ID, USER_ID, TOKEN, CREATE_AT) VALUES (2, 200, 1, 'p0190', 23, 'j6I', now());
INSERT INTO SPREAD (SPREAD_ID, AMOUNT, PERSON, ROOM_ID, USER_ID, TOKEN, CREATE_AT) VALUES (3, 300, 4, 'BC88', 24, 'dXp', now());


INSERT INTO PICKUP (PICKUP_ID, AMOUNT, SPREAD_ID, VERSION) VALUES (1, 80, 1, 0);
INSERT INTO PICKUP (PICKUP_ID, AMOUNT, SPREAD_ID, VERSION) VALUES (2, 7, 1, 0);
INSERT INTO PICKUP (PICKUP_ID, AMOUNT, SPREAD_ID, VERSION) VALUES (3, 3, 1, 0);
INSERT INTO PICKUP (PICKUP_ID, AMOUNT, SPREAD_ID, VERSION) VALUES (4, 10, 1, 0);

INSERT INTO PICKUP (PICKUP_ID, AMOUNT, SPREAD_ID, VERSION) VALUES (5, 200, 2, 0);

INSERT INTO PICKUP (PICKUP_ID, AMOUNT, SPREAD_ID, VERSION) VALUES (6, 100, 3, 0);
INSERT INTO PICKUP (PICKUP_ID, AMOUNT, SPREAD_ID, PICK_ID, PICK_AT, VERSION) VALUES (7, 50, 3, 6674, now(), 0);
INSERT INTO PICKUP (PICKUP_ID, AMOUNT, SPREAD_ID, VERSION) VALUES (8, 1, 3, 0);
INSERT INTO PICKUP (PICKUP_ID, AMOUNT, SPREAD_ID, VERSION) VALUES (9, 49, 3, 0);


